NUTRITION_HINTS = {
    "chicken": {"protein": "high", "fat": "medium", "note": "strong protein source"},
    "beef": {"protein": "high", "fat": "high", "note": "high protein but can raise fat level"},
    "egg": {"protein": "high", "fat": "medium", "note": "protein-rich and common allergen"},
    "milk": {"protein": "medium", "fat": "medium", "note": "dairy allergen risk"},
    "yogurt": {"protein": "medium", "fat": "medium", "note": "dairy-based ingredient"},
    "cheese": {"protein": "medium", "fat": "high", "note": "dairy and salt risk"},
    "lentils": {"protein": "high", "carb": "medium", "fiber": "high", "note": "plant protein and fiber"},
    "beans": {"protein": "high", "carb": "medium", "fiber": "high", "note": "plant protein and fiber"},
    "chickpeas": {"protein": "high", "carb": "medium", "fiber": "high", "note": "plant protein and fiber"},
    "rice": {"carb": "high", "note": "main carbohydrate source"},
    "pasta": {"carb": "high", "note": "main carbohydrate source"},
    "bread": {"carb": "high", "note": "gluten source"},
    "potato": {"carb": "high", "note": "starchy carbohydrate"},
    "olive oil": {"fat": "high", "note": "healthy fat source"},
    "butter": {"fat": "high", "note": "high saturated fat and dairy"},
    "sugar": {"sugar": "high", "note": "raises sugar risk"},
    "honey": {"sugar": "high", "note": "natural sugar but still sugar risk"},
    "salt": {"salt": "high", "note": "raises sodium risk"},
    "spinach": {"vitamin": "high", "fiber": "medium", "note": "strong micronutrient signal"},
    "tomato": {"vitamin": "medium", "fiber": "medium", "note": "freshness and vitamin signal"},
    "banana": {"carb": "medium", "vitamin": "medium", "sugar": "medium", "note": "fruit sugar and potassium"},
    "avocado": {"fat": "high", "fiber": "medium", "note": "healthy fat and premium positioning"},
    "nuts": {"protein": "medium", "fat": "high", "allergen": "tree nuts", "note": "allergen and healthy fat"},
    "peanut": {"protein": "medium", "fat": "high", "allergen": "peanuts", "note": "major allergen"},
    "shrimp": {"protein": "high", "allergen": "shellfish", "note": "shellfish allergen"},
    "fish": {"protein": "high", "fat": "medium", "allergen": "fish", "note": "protein and omega-fat signal"},
    "wheat": {"carb": "high", "allergen": "gluten", "note": "gluten source"},
}

ALLERGEN_KEYWORDS = {
    "milk": "dairy",
    "cheese": "dairy",
    "yogurt": "dairy",
    "butter": "dairy",
    "egg": "egg",
    "peanut": "peanuts",
    "nuts": "tree nuts",
    "almond": "tree nuts",
    "cashew": "tree nuts",
    "wheat": "gluten",
    "bread": "gluten",
    "pasta": "gluten",
    "shrimp": "shellfish",
    "fish": "fish",
    "soy": "soy",
}
